export const appConstants = {
  Occasions: [
    "Birthday & Celebrations",
    "Congrats & Praise",
    "Farewell",
    "Sympathy & Get Well",
    "Thank You",
    "Welcome & Onboarding",
    "Years of Service Anniversary",
    "Christmas",
    "Easter",
    "Father's Day",
    "Graduation",
    "Halloween",
    "Love",
    "Memorial",
    "Mother's Day",
    "New Baby",
    "New Year's",
    "Retirement",
    "Staff Appreciation Days",
    "Valentine's Day",
    "Wedding & Anniversary",
  ],
};
